#!/bin/sh

pwd | grep '/dev/' >/dev/null 2>/dev/null

if [ $? = 0 ] ; then
  export DEV='/dev'
fi

/bin/echo -n > volist.tmp
/bin/echo -n > for.html

cat <<EOF >all-vos.pipe
{
  "cache_seconds": 3600,
  "machinetypes":
  [
EOF

(
cat <<EOF
 1 cernvm4 cernatschool.org 
 1 cernvm4 comet.j-parc.jp
 1 cernvm4 dune 
 1 cernvm4 gridpp 
 8 cernvm4 gridpp 
 1 cernvm4 hyperk.org 
 1 cernvm4 lsst
 4 cernvm4 lsst
 1 cernvm4 lz 
 1 cernvm4 magrid 
 1 cernvm4 mice 
 1 cernvm4 na62.vo.gridpp.ac.uk 
 1 cernvm4 pheno 
 1 cernvm4 skatelescope.eu
 8 cernvm4 skatelescope.eu
 1 cernvm4 snoplus.snolab.ca 
 1 cernvm4 solidexperiment.org 
 1 cernvm4 t2k.org 
 1 cernvm4 vo.moedal.org 
 1 cernvm4 vo.northgrid.ac.uk 
 1 cernvm4 vo.scotgrid.ac.uk 
EOF
) | (

while read processors cernvmVersion vo
do

export processors cernvmVersion vo

if [ $processors -gt 1 ] ; then
  export processors_str="$processors"
  export dirac_opts="--maxNumberOfProcessors $processors --tag MultiProcessor --tag ${processors}Processors --requiredTag ${processors}Processors"
else
  export processors_str=""
  export dirac_opts=""
fi

export dirac_opts="$dirac_opts -o /Resources/Computing/CEDefaults/SubmitPool=Pool_$vo -o /Resources/Computing/CEDefaults/VirtualOrganization=$vo -g v13r0"

export vohyphens=`echo $vo | sed 's/\./-/g'`

# NB this is repeated in the all-vos.pipe file below too

cat <<EOF >$vohyphens$processors_str.pipe
{
  "cache_seconds": 3600,
  "machinetypes":
  [
   {
    "accounting_fqan": "/$vo/Role=NULL/Capability=NULL",
    "backoff_seconds": 600,
    "fizzle_seconds": 600,
    "heartbeat_file": "heartbeat",
    "heartbeat_seconds": 600,
    "machine_model": "cernvm3",
    "min_wallclock_seconds": 50000,
    "max_wallclock_seconds": 100000,
    "min_processors": $processors,
    "max_processors": $processors,
    "root_image": "https://repo.gridpp.ac.uk/vacproject$DEV/gds/$cernvmVersion.iso",
    "suffix": "vm$processors_str-$vohyphens",
    "target_share": 1.0,
    "user_data": "https://repo.gridpp.ac.uk/vacproject$DEV/gds/pilot/user_data_vm",
    "user_data_file_hostcert": "hostcert.pem",
    "user_data_file_hostkey": "hostkey.pem",
    "user_data_option_dirac_opts": "$dirac_opts",
    "user_data_option_vo": "$vo"
   }
  ]
}
EOF
  
if [ "$needcomma" != "" ] ; then
  echo ',' >> all-vos.pipe
  /bin/echo ', ' >> volist.tmp
  /bin/echo -n ', ' >> for.html
else
  needcomma="yes"
fi
  
/bin/echo -n "$vo" >> volist.tmp
/bin/echo -n "gds-vm$processors_str-$vohyphens" >> for.html

cat <<EOF >>all-vos.pipe
   {
    "accounting_fqan": "/$vo/Role=NULL/Capability=NULL",
    "backoff_seconds": 3600,
    "fizzle_seconds": 600,
    "heartbeat_file": "heartbeat",
    "heartbeat_seconds": 600,
    "machine_model": "cernvm3",
    "min_wallclock_seconds": 50000,
    "max_wallclock_seconds": 100000,
    "min_processors": $processors,
    "max_processors": $processors,
    "root_image": "https://repo.gridpp.ac.uk/vacproject$DEV/gds/$cernvmVersion.iso",
    "suffix": "vm$processors_str-$vohyphens",
    "target_share": 1.0,
    "user_data": "https://repo.gridpp.ac.uk/vacproject$DEV/gds/pilot/user_data_vm",
    "user_data_file_hostcert": "hostcert.pem",
    "user_data_file_hostkey": "hostkey.pem",
    "user_data_option_dirac_opts": "$dirac_opts",
    "user_data_option_vo": "$vo"
   }
EOF

done
)

cat <<EOF >>all-vos.pipe
  ]
}
EOF

sed 's/"target_share": 1.0/"target_share": 0.0/' all-vos.pipe > all-vos-zero-shares.pipe

echo >> for.html
echo >> for.html
echo `sort volist.tmp | uniq` >> for.html
rm -f volist.tmp
